import { renderToStaticMarkup } from 'react-dom/server';
import RootLayout, { metadata } from '../../src/app/layout';

jest.mock('next/font/google', () => ({
  Geist: () => ({ variable: 'font-geist-sans' }),
  Geist_Mono: () => ({ variable: 'font-geist-mono' }),
}));

describe('root layout', () => {
  it('exports expected metadata', () => {
    expect(metadata.title).toBe('Create Next App');
    expect(metadata.description).toBe('Generated by create next app');
  });

  it('renders layout shell with expected classes', () => {
    const html = renderToStaticMarkup(
      <RootLayout>
        <main>Template Content</main>
      </RootLayout>
    );

    expect(html).toContain('<html lang="en">');
    expect(html).toContain('font-geist-sans font-geist-mono antialiased');
    expect(html).toContain('Template Content');
  });
});
